language: d

d: dmd-2.079.1

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
  - dub build -b release

after_success:
  - "tar caf txtproc-${TRAVIS_COMMIT}-x86_64.tar.gz txtproc/"

